http:
  port: 8080
  host: "0.0.0.0"

cors:
  allowedOrigins: "*"
  allowedMethods: [ "GET", "POST", "PUT", "DELETE" ]
  allowedHeaders: [ "Content-Type", "Authorization" ]

staticConfig:
  webRoot: "static"

logging:
  level: "INFO"

certificate:
  storageMode: "in-memory" # in-memory | file
  initialUserCertificates: 1
  initialLegalCertificates: 1
  certsPath: "certs/"
  caCertPath: "certs/ca-default.crt"
  keySize: 2048
  keyFactoryType: "RSA"
  signatureAlgorithm: "1.2.840.113549.1.1.11"
  keystorePassword: "123456"
  caValidityYears: 10
  userValidityYears: 1
